# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

jobs:

- job: macOS

  pool:
    vmImage: 'macOS-10.14'

  variables:
    solution: '**/*.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'

  steps:
  - script: sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 5_18_1
    displayName: 'Select Xamarin SDK version'
  - script: |
      set -e
      git submodule update --init --recursive

      brew install autoconf
      brew install automake

      cd monodevelop
      ./configure --profile=mac
      make

- job: Windows

  pool:
    vmImage: 'VS2017-Win2016'

  variables:
    solution: '**/*.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'

  steps:
  - script: |
      git submodule update --init --recursive
  - script: |
      make.bat
  - script: |
      after_build.bat
